#
# Copyright (c) 2024 Oak Ridge National Laboratory.
#
# This file is part of Myna. For details, see the top-level license
# at https://github.com/ORNL-MDF/Myna/LICENSE.md.
#
# License: 3-clause BSD, see https://opensource.org/licenses/BSD-3-Clause.
#
"""Define output file formats and database sync behavior.

To implement a new option for a file type, a subclass of File
(defined in myna.files.file) should be added to an existing
module if related to existing files or added to a new module.

Subclasses of File are responsible for implementing the
File.file_is_valid() function. This function is used to
check if the expected output was generated by a workflow
component.
"""

from .file import *
from .file_region import *
from .file_gv import *
from .file_id import *
from .file_reduced_solidification import *
from .file_vtk import *
from .file_temperature import *
from .file_melt_pool_geometry import *
from .file_exodus import *
from .file_depth_map import *
