#!/bin/bash
# Script to run a specified ExaCA case using
# the specified executable and mpi_run parameters
#
# Usage:
#   ./runCase <case_dir> <exec_path> <mpi_run>

root_dir=$(pwd)

# Check if a valid case directory is provided
# If not, assume execution in file directory
if [ -z "$1" ]; then
    echo "WARNING: Directory path argument is missing."
    echo "Usage: $0 <case_dir> <exec_path> <mpi_run>"
    exit 1
else
    case_dir="$1"
    # Check if the provided path is a valid directory
    if [ ! -d "$1" ]; then
        echo "Error: The provided argument is not a valid directory."
        echo "Usage: $0 <case_dir> <exec_path> <mpi_run>"
        exit 1
    fi
fi

# Check if an executable was provided
if [ -z "$2" ]; then
    echo "Error: No ExaCA executable was provided"
    exit 1
else
    EXACA_EXE_PATH="$2"
    # Check that the provided executable is valid
    if [ ! -x "$2"]; then
        echo "Error: The provided ExaCA executable is not a valid executable."
        echo "Usage: $0 <case_dir> <exec_path> <mpi_run>"
        exit 1
    fi
fi

# Check if an mpi_run command has been specified
# If not, check if $mpi_run exists as environmental variable
if [ -z "$3" ]; then
    mpi_run=$2
elif [ -z "$mpi_run" ]; then
    echo "No value for $mpi_run found."
    echo "Usage: $0 <case_dir> <exec_path> <mpi_run>"
    exit 1
fi

# Get corresponding Myna directories
rve_dir="$(dirname "$case_dir")"
part_dir="$(dirname "$rve_dir")"
myna_results_dir="$(dirname "$part_dir")"
MYNA_SIM_PATH="$(dirname "$myna_results_dir")"

# Update input files
sed -i "s@MYNA_SIM_PATH@$MYNA_SIM_PATH@g" $case_dir/inputs.json
sed -i "s@EXACA_EXE_PATH@$EXACA_EXE_PATH@g" $case_dir/inputs.json
cat $case_dir/inputs.json
echo "Input path = $case_dir/inputs.json"

# Run the ExaCA case
$mpi_run $EXACA_EXE_PATH/bin/ExaCA-Kokkos $case_dir/inputs.json
