"""Define output file formats and database sync behavior.

To implement a new option for a file type, a subclass of File
(defined in myna.files.file) should be added to an existing
module if related to existing files or added to a new module.

Subclasses of File are responsible for implementing the
File.file_is_valid() function. This function is used to
check if the expected output was generated by a workflow
component.
"""

from myna.files.file import *
from myna.files.file_region import *
from myna.files.file_gv import *
from myna.files.file_id import *
from myna.files.file_reduced_solidification import *
from myna.files.file_vtk import *
